vrnetlab/vrnetlab

README.md, vrnetlab.sh
Wrote some shorthands for connecting to ssh and console from the shell.
=> Shell shorthands for ssh and console access

README.md, vrnetlab.sh
Added a shell shorthand for creating bridges.
=> Shell shorthand for creating bridges

config-engine-lite/configengine
=> Removed the god exception handler

config-engine-lite/configengine
=> Changed Router.get_address to first lookup router name 

README.md, csr/Makefile, csr/README.md, csr/docker/Dockerfile, csr/docker/launch.py
Added support for CSR1000v, to be able to get the console on serial(instead of vga) I needed to first create a temporary docker image and after the bootstrap configuration is completed saving the state with 'docker commit'.
=> Added support for Cisco CSR1000v

config-engine-lite/configengine, topology-machine/topomachine
Basic support for CSR1000v in topomachine, ugly hack for weird interface mappings, this is probably something that can easily be improved upon.
=> Added support for CSR1000v in topomachine

README.md, csr/README.md, sros/README.md, veos/README.md, vmx/README.md, xrv/README.md
=> Updated documentation about the "latest" tag.

config-engine-lite/README.md, config-engine-lite/configengine
- Added functionality to apply configuration to a single router (--config and --router)
- Added a --wait-for-boot feature that blocks the connect call until the router is available over SSH or a timeout is reached.
=> Added functionality to apply a configuration template to a single router

csr/README.md, csr/docker/launch.py, topology-machine/topomachine
=>  Lower the default amount of nics for CSR

topology-machine/Dockerfile, topology-machine/Makefile, topology-machine/README.md
=> Build a container image out of topomachine

csr/Makefile
=> CSR: Updated Makefile to avoid name collision

README.md
=> Add note about exposing SNMP to documentation.

common/vrnetlab.py
Also alphabetize imports to not trigger my CDO.
=> Import missing time module required since 22e0097.

vrnetlab.sh
i found this useful for various things.
=> add vrsftp function to vrnetlab.sh

topology-machine/topomachine
prefix support is broken, this patch fixes it.
i've been using this fix for some time now, so its been tested somewhat.
=> fix prefix support

xrv9k/docker/launch.py
Backwards incompatible arg name change. Sorry :/
=> Bump XRv mem & change --nics to --num-nics

vmx/docker/launch.py
Move `base_vcp_dir` to an attribute instead of recomputing in property. I missed this change when removing the version parsing code from the launcher.
=> Fix vmx launch script

vr-xcon/Dockerfile, vr-xcon/README.md, vr-xcon/xcon.act, vr-xcon/xcon.py
A littl experimental right now. This xcon is implemented in Acton. I think the actor model is a great fit here for doing error handling etc. Quite natural. The whole state tracking was a bit of a POC. Maybe should be removed.
The new xcon is automatically compiled and included in the container image so we can easily run it by switching entrypoint!
=> Add new xcon

.github/workflows/test.yml, .gitlab-ci.yml, Makefile, topology-machine/topomachine
Let's build `nxos9kv` in CI too. We have an image!
=> CI for nxos9kv

common/vrnetlab.py
Recent versions of QEMU, like the one that ships with Debian Bookworm, started requiring users to specify the backing image format when creating an overlay image with 'qemu-img create'. I have seen files where the extension did not match the format so I guess from the perspective of QEMU it makes sense to be explicit. To make this transparent to the users of vrnetlab  we use 'qemu-img info' to detect the format and then feed it back to 'qemu-img create'!?
Originally identified by @tacerus in #323.
=> Detect backing image format with qemu-img

vr-bgp/Dockerfile, vr-bgp/README.md, vr-bgp/bgpapi.py
This addition to the vr-bgp API makes it possible to ping an address from an announced prefix.
=> Configure pingable address for announced prefix

.github/workflows/test.yml, .gitlab-ci.yml, Makefile, topology-machine/topomachine, ucpe-oneos/.gitattributes, ucpe-oneos/Makefile, ucpe-oneos/README.md, ucpe-oneos/docker/Dockerfile, ucpe-oneos/docker/launch.py
The Ekinops uCPE is a CPE with a hypervisor, allowing service providers to deploys individual VNFs or service chains on the edge.
The license is tied to UUID, so we also support injecting a static UUID.
Tested with 3.7.5 and 3.8.1.
=> Add ucpe-oneos

.github/workflows/test.yml, xrv/docker/launch.py, xrv9k/docker/Dockerfile, xrv9k/docker/launch.py
Some QOL improvements for newer versions of IOS XR.
=> xrv9k sync
