csr/README.md

Updated with information about the interface mapping issue, including which versions that I have tested that do and do not exhibit this behavior.

Updated CSR100v readme about issues with interface mapping

---

vr-bgp/exabgp.conf.tpl
vr-bgp/vr-bgp.py

Add option `--allow-mixed-afi-transport` to override default.

Limit announcement of specific AFI routes to transport (neighbor) family.

---

config-engine-lite/README.md
config-engine-lite/configengine

Now you can specify --attr key=value once for each attribute instead of providing a comma separated list in a single string.

Fixed ugly --attrs list syntax

---

topology-machine/topomachine

subprocess.Popen requires either a single string or a list of args. topomachine is using a mix of a list of args and strings containing multiple args. this is causing the starting of containers to fail. this patch makes each arg its own list element.

fix cmd args so that each arg/value is its own list element.

---

vr-bgp/README.md
vr-bgp/bgpapi.py

This adds support for defining a custom as-path for announced prefix, allowing us to create a fake transit peer. If omitted, the default value for this attribute is the local AS.
Example prefix announced from AS 21, originating from AS 1234 `{ 'prefix': '21.1.0.0/24', 'as-path': [21, 1234] }`.

Add support for `as-path` attribute for prefix.

---

vr-bgp/bgprec.py
vr-bgp/exabgp.conf.tpl
vr-bgp/vr-bgp.py

This MR adds a default `listen` statement to exabgp configuration.
For easier testing during development (especially when connecting vr-bgp instances back-to-back), it is useful to have vr-bgp instances listen for incoming connections on 179/TCP as well.
Additionally, this MR fixes parsing of updates exchanged between two vr-bgp instances directly connected.

Add neighbor listen by default

---

vr-bgp/exabgp.conf.tpl
vr-bgp/vr-bgp.py

We enabled listening by default, which really does make sense. There seems to
be a bug around how we pick up the state of a neighbor however. I'm not
entirely sure if we are doing the wrong thing or if it's a bug in ExaBGP. Until
it has been resolved we are going to disable listening per default and instead
have this --listen option to selectively enable it if and when needed. Once the
neighbor state issue has been resolved I reckon we can listen per default
again.

Add --listen argument

---

openwrt/Makefile
openwrt/README.md
openwrt/docker/Dockerfile
openwrt/docker/launch.py

Hi,
Thought this one might be funny :-) 
OpenWRT is a cool platform, with https://www.gl-inet.com/ and such. Could use this to mimic "home devices" or whatnot.
What do you think, could this be of interest to people?
/Fredrik
SSH login:
```
vrnetlab@172.17.0.2's password:
BusyBox v1.23.2 (2015-07-25 08:11:38 CEST) built-in shell (ash)
_______                     ________        __
|       |.-----.-----.-----.|  |  |  |.----.|  |_
|   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
|_______||   __|_____|__|__||________||__|  |____|
|__| W I R E L E S S   F R E E D O M
-----------------------------------------------------
CHAOS CALMER (15.05, r46767)
-----------------------------------------------------
* 1 1/2 oz Gin            Shake with a glassful
* 1/4 oz Triple Sec       of broken ice …
```

openwrt to the people

---

vr-bgp/Dockerfile

Since 6ec2880f6ae8a0384eed7c93c6c76970c4fed885, `sysctl` command is used by vr-bgp. This PR installs the command as it is missing in debian:stable image.

Install procps to make sysctl command available.

---

vqfx/README.md
vqfx/docker/launch_vqfx.py

With only 1024MB RAM given to `VQFX_vcp`, we got frequent kernel panics early in the boot process. Increasing to 2048MB seems to work.
```
Calling dcf_ng_hw_init for platform hw vecs initialization
panic: pmap_mapdev: Couldn't alloc kernel virtual memory
KDB: stack backtrace:
kdb_backtrace(b0e5725b,b1f55c80,b0e425a0,b2421b80,0) at kdb_backtrace+0x29
panic(b0e425a0,d423c000,1f,b2421c50,b2421c04) at panic+0x283
pmap_mapdev(3ffe201f,d423b0b4,b2421bd4,b0526712,3ffe201f) at pmap_mapdev+0x71
AcpiOsMapMemory(3ffe201f,0,d423b0b4,b2421bc4,b2421bcc) at AcpiOsMapMemory+0x18
AcpiTbGetThisTable(b2421c44,b2421c04,b2421c50,0,b2421c04) at AcpiTbGetThisTable+0xe4
AcpiTbGetTableBody(b2421c44,b2421c04,b2421c50,d423a0b4,d423b0b4) at AcpiTbGetTableBody+0x47
AcpiTbGetTable(b2421c44,b2421c50,9,3ffe201f,0) at …
```

Increase `VQFX_vcp` RAM to 2048 to avoid kernel panics.

---

topology-machine/topomachine

The vQFX, even though it is technically a switch, is still configured via the `routers` dict in hltopo.json. It made sense to me, since topomachine isn't really aware of the function anyway.

Add support for vQFX to topomachine

---

topology-machine/topomachine

The original generated `links` dict makes it difficult to find peers and their interfaces for a given router.
An example for a p2p link between bgp1(tap0) - r1(xe-0/0/1):
```
"links_by_nodes": {
"bgp1": {
"r1": {
"our_interface": "tap0",
"our_numeric": 1,
"their_interface": "xe-0/0/1",
"their_numeric": 2
}
},
"r1": {
"bgp1": {
"our_interface": "xe-0/0/1",
"our_numeric": 2,
"their_interface": "tap0",
"their_numeric": 1
}
}
}
```

topomachine also generates a `links_by_nodes` dict in lltopo.

---

veos/Makefile

Arista uses a slightly different naming convention for pre-release images. Update the regexp in the veos `Makefile` to support these version names.

update veos makefile to match EFT release names

---

vr-bgp/Dockerfile
vr-bgp/Makefile

The vr-bgp image uses vr-xcon as a _FROM_. However, it had a hardoded
`vrnetlab/vr-xcon` image name, implying the usage of the public Docker
Hub image.
If you wanted to use a private registry by setting the env var
`$DOCKER_REGISTRY`, the built images were tagged correctly, but vr-bgp
actually still used the Docker Hub image.
By using a build _ARG_ in _FROM_ for vr-bgp, this is avoided.

Improve docker images build for private registries.

---

vr-bgp/vr-bgp.py
vr-xcon/README.md
vr-xcon/xcon.py

This PR adds a new feature to `xcon.py` - the ability to set up IP addressing + VLAN ID on the overlay _tap_ interface. Of course, this only applies to the _Tcp2Tap_ mode. I updated the documentation with an usage example.
This new feature is now also used from vr-bgp to configure the overlay address.

Move IP addressing setup from vr-bgp to vr-xcon

---

makefile-sanity.include
vr-bgp/exabgp.conf.tpl
vr-bgp/vr-bgp.py

Hi,
I've added the ttl-security ExaBGP option to vr-bgp.
Also, the build was failing if the REGISTRY env variable wasn't set, so I've put the default to "vrnetlab/"
Both done per @mzagozen 's suggestions.

Add support for exabgp "ttl-security" setting to vr-bgp

---

makefile-sanity.include

Regexp modified to allow docker registry name like this: VEL99-REGISTRY-1:5000

Allow '-' in docker registry name

---

common/vrnetlab.py

If the overlay disk image is overwritten every time we start the router the running-configuration is lost for the CSR and the router defaults to console output over vga instead of serial.
I think this is the correct fix for @jabelk problem in issue #160 
Tested with xrv and csr.

Only create overlay disk once.

---

common/vrnetlab.py

Attempting to fix #160.
I've tested my code against 2 lots of vEOS versions and also a CSR to ensure that still works

vEOS requires it's ma1 interface to be the first interface in the bus

---

vmx/docker/launch.py

This fixes misalignment of vmx v17.2R1.13 interfaces for xconn

Add dummy interface to 17.2R1.13

---

openwrt/download.py

Hi, 
I couldn't download/generate docker images for OpenWRT.
It seems that URL href for some version has changed(some relative, some absolute).
This fix downloads targets from proper path.
Also, this includes fix for minor bug in renaming local filename, adds version string to them.
Makefile expects every image filename includes version string, while they are typically just "combined-ext4.img".
before
```
% make build 
python3 download.py
OpenWrt 18.06.4 releases/18.06.4/targets/ https://downloads.openwrt.org/releases/18.06.4/targets/x86/kvm_guest/
LEDE 17.01.6 releases/17.01.6/targets/ https://downloads.openwrt.org/releases/17.01.6/targets/x86/kvm_guest/
OpenWrt 18.06.3 http://archive.openwrt.org/releases/18.06.3/targets/ https://downloads.openwrt.org/http://archive.openwrt.org/releases/1 …
```

fix openwrt's download.py: download url and local filename

---

vmx/Makefile
vmx/docker/launch.py

This adjusts the regexes used in the vMX packaging to support images with custom build versions (i.e. a -D in the version)

Add suport for custom vMX builds

---

vmx/docker/launch.py

QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u2) throws the below error (Please see issue #210 for details)
> 2019-09-19 22:21:23,064: vrnetlab INFO STDERR: qemu-system-x86_64: -usbdevice disk:format=raw:/vmx/metadata-usb-re.img: '-usbdevice' is deprecated, please use '-device usb-...' instead
qemu-system-x86_64: -usbdevice disk:format=raw:/vmx/metadata-usb-re.img: could not add USB device 'disk:format=raw:/vmx/metadata-usb-re.img'
2019-09-19 22:21:23,066: vrnetlab INFO Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 1)
The commit fix that issue by replacing obsolete options with the newer one.
c839819

Replacing obsolete 'usbdevice' option

---

common/vrnetlab.py

When using more than 99 nics, this function does not
work as expected. Instead of arithmetic, it relies on simply
prefixing a value of i with 100.
Closes #223

Modify gen_nics() to assign correct ports > 99

---

makefile-install.include

The committed image after running vMX install has an additional layer
containing the modifications done during installation. The previous
layers are the same though. When comparing the layers of the previously
tagged image with the current build, we must omit the last layer.

Fix modifications detection for build & install images

---

vmx/docker/launch.py

The VFPC VMX images has a different login name (qemux86-64 vs localhost).
This will add "qemux86-64 login" to what we look for if the VFPC has booted.
This has been tested on: 18.4R1.8, 18.4R3.3, 19.4R3.11 and 20.4R1.12.

Add VFPC login expect string for newer VMX images

---

makefile-install.include

Commit 5611463 removed the entrypoint from the docker commit and since this change vmx images have been booted into install mode.

Reinstate docker commit entrypoint to clear CMDs

---

common/vrnetlab.py
nxos9kv/Makefile
nxos9kv/README.md
nxos9kv/docker/Dockerfile
nxos9kv/docker/launch.py
nxos9kv/nxos_config.txt

This MR adds support for NX-OS 9000v. This is different from the Titanium emulator based image built in the current `nxos` directory.
This has been tested with release 9.3(7).
Please see nxos9kv/README.md for details.

Add NX-OS 9000v

---

veos/Makefile

Ensures we don't try to build with vEOS64 images, which is non-functional

Make image matching glob less greedy, fixes #273

---

topology-machine/topomachine

This adds veos support for topomachine generation.
This change needs the change in #256 to not be off by one on every interface.

Add veos support to topomachine

---

vmx/docker/Dockerfile
vmx/docker/juniper.conf
vmx/docker/launch.py

This commit adds support for gRPC and GNMI in Juniper vMX routers.
Includes:
- Dockerfile: expose the container's 57400 TCP port
- juniper.conf: add configuration knob to enable JUNOS clear-text and unauthenticated gRPC interface
- launch.py: `vrnetlab.HOST_FWDS` defines the list of ports to be forwarded. Edit launch.py to append the TCP/57400:57400 forwarding
Port 57400 is used for uniformity with [78da58e](https://github.com/vrnetlab/vrnetlab/pull/285/commits/78da58e7c513ee85956154cea54991fd25d563e3) as there is no officially assigned port or a default for JunOS devices.
Tested for JunOS 20.4R3.8 for vMX

Add gRPC support for vMX

---

common/vrnetlab.py
xrv9k/Makefile
xrv9k/docker/launch.py

This MR adds a new option `--install` for `xrv9k`.
When the vanilla image from Cisco starts up, it takes a long time to install various packages. This happens every time a VR is started. With the `--install` option and Makefile changes, the packages are pre-installed during the docker image build, reducing the start time when this image is used.
The images created with the `--install` option starts up in half of the time compared with previous images.
However the newly created image is about 3 times larger than previous one.

Add install to xrv9k

---

config-engine-lite/Dockerfile
config-engine-lite/configengine

As described in #230 it is not possible to build the container image for `config-engine-lite`. Python 2.7 is a dead end and Xenial only includes Python 3.5. Instead of trying to figure out which version of pip, napalm and other dependencies still works with these old Python versions I tried updating the base image to Jammy and then use Python 3.10. It works, at least the simple test for applying the template listed in the readme!

Fix config-engine-lite container image

---

common/vrnetlab.py
vrp/docker/launch.py
xrv9k/docker/launch.py

The Huawei VRP devices boot up and present the login prompt before all components are running. If we try to configure the device immediately after the vrnetlab container starts up and reports healthy, some interfaces may still be missing! This MR adds interface detection to bootstrap script and will prevent the container from becoming healthy until the expected GigabitEthernet interfaces show up.

Improve VRP

---

common/vrnetlab.py
csr/docker/Dockerfile
nxos/docker/Dockerfile
nxos9kv/docker/Dockerfile
nxos9kv/docker/launch.py
openwrt/docker/Dockerfile
routeros/docker/Dockerfile
sros/docker/Dockerfile
topology-machine/Dockerfile
veos/docker/Dockerfile
vmx/docker/Dockerfile
vmx/docker/launch.py
vqfx/docker/Dockerfile
vr-xcon/Dockerfile
vrp/docker/Dockerfile
vsr1000/docker/Dockerfile
xrv/docker/Dockerfile
xrv9k/docker/Dockerfile

The `stretch` release was removed from the package repositories (or rather all packages were removed from the `stretch` repos). Anyway, `stretch` was long in the tooth when #201 was first opened and now we have no choice but to upgrade to fix image builds. 
Because QEMU & friends are also upgraded this branch now includes a fix for overlay disk image creation per VM instance. This is no longer allowed (a write lock prevents it) to share a disk image across multiple guests. vrnetlab did exactly the same when running a network device in distributed mode - a VM for control plane and one or more VMs for the forwarding plane. Why that worked at all is puzzling, but it cannot be done using new QEMU without an extra NBD layer anyway. 
This project (on github) does not include CI, but we have a …

Use debian bullseye

---

ci-builder-image/Dockerfile

Ubuntu Yakkety package repos are gone, if we want to rebuild the CI image we must upgrade Ubuntu ...
Below is the difference in installed package versions. The biggest risk is Docker IMHO, but we don't do anything super advanced with it that would break with the new version?
```
root@41c1874359a6:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
root@41c1874359a6:/# git --version
git version 2.9.3
root@41c1874359a6:/# git-lfs version
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
root@41c1874359a6:/# docker --version
Docker version 1.12.6, build 78d1802
root@41c1874359a6:/# curl --version
curl 7.50.1 (x86_64-pc-linux-gnu) libcurl/7.50.1 GnuTLS/3.5.3 zlib/1.2.8 libidn/1.33 librtmp/2.3
Protocols: dict file ftp ftps …
```

Upgrade vrnetlab/ci-builder image to Ubuntu Jammy

---

common/vrnetlab.py
csr/Makefile
csr/docker/Dockerfile
csr/docker/launch.py
makefile.include
vmx/docker/Dockerfile
vmx/docker/launch.py

IOS XE 16+ changed the `ip domain name ` command. Rather than trying to parse the version out from the disk image in the launch script, I opted to reuse the version extraction regex in the makefile. The `VERSION` variable is already used to create the container image tag, it is now also passed to the launch script via an environment variable.
Closes #312

IOS XE domain-name

---

vr-xcon/xcon.act

We have many `TcpEndpoint` actors all pushing their internal state changes to the `Healthcheck` actor with `Healthcheck.update()`. These calls are serialized and processed in the order they arrive (?). The internal `Healthcheck._flush()` method then uses a single `file.WriteFile` actor to serialize writes to the "/health" file. If we did not do that and used a *new* `file.WriteFile` actor directly (like we used to), there is a race between the different `file.WriteFile` actors and a chance of inconsistent state written to the file.

Use single WriteFile actor for serializing file writes

---

topology-machine/topomachine

`topomachine` can now use *xcon-ng* where applicable - only p2p links are supported.

Add xcon-ng support to topomachine

---

topology-machine/README.md
topology-machine/example-hltopo.json
topology-machine/topomachine

topomachine already supports `run_args` for passing a raw string containing all the arguments to a container. With `run_args_structured` we can keep the structure in JSON and then pass the arguments as:
- a list,
- as key value pairs
to the container. Note how the values are passed verbatim - there are no assumptions about prefixing the key names with '--' or quoting the values.

Extend 'run_args' in topomachine to support lists, dicts

---

makefile-install.include
makefile.include
nxos9kv/Makefile
veos/Makefile
vmx/Makefile
vmx/README.md
vmx/docker/Dockerfile
vmx/docker/launch.py
vqfx/Makefile

The vMX image builder now supports bundling a license file with the installed image - simply place the `JUNOS12345789.lic` file in the `vmx/docker` directory.
Note: the license file is not only copied to the bootstrap drive, but also remains in the root folder of the docker image. To avoid that we could pass the license to the installer as an env var, but is it worth it?

Bundle license with vmx

---

xrv/Makefile
xrv9k/Makefile

Support double-digit version numbers in xrv(9k)

---

common/vrnetlab.py
csr/docker/launch.py
nxos/docker/launch.py
nxos9kv/docker/launch.py
openwrt/docker/launch.py
routeros/docker/launch.py
sros/docker/launch.py
veos/docker/launch.py
vqfx/docker/launch.py
vrp/docker/launch.py
vsr1000/docker/launch.py
xrv/docker/launch.py
xrv9k/docker/launch.py

*Always* create the overlay disk image to avoid the potentially expensive copy-on-write operation for large files. We used to create overlay images right in `vrnetlab.VM.__init__()`. This makes it difficult to implement the `restart()` method correctly. The restart method is used to recover from an incorrect state so all modifications to the original image should be discarded.

Delay overlay image creation until QEMU starts

---

.github/workflows/test.yml
.gitlab-ci.yml
Makefile
topology-machine/Dockerfile
topology-machine/Makefile
topology-machine/README.md
topology-machine/example-lltopo.json

- Add CI test for the topomachine container
- Install extra tools (git, make) that make it possible to use the topomachine image directly in CI for keeping generated outputs (lltopo, scripts) up to date

Build (with) topomachine container in CI

---

topology-machine/README.md
topology-machine/topomachine

This PR proposes a new `--keep-order` option for topomachine that takes into account the order in which *p2p* links and routers in *fullmeshes* are defined. When topomachine produces the low-level topology JSON (`--build` command) it first sorts the routers and links. As far as I can tell this was added back in the day when iterating a Python dictionary was not guaranteed to be in any order (of insertion or otherwise sorted) as a means of guaranteeing stable output ✝️. And it does work, but sometimes the assigned interface IDs are unexpected. Take this topology definition, consisting of 3 "core" routers connected in full mesh and each code router has a pc attached.
```json
{
"routers": {
"vr1": { "type": "vmx" },
"vr2": { "type": "vmx" },
"vr3": { "type": "vmx" },
"pc1": { "type": "vmx" …
```

Add --keep-order to topomachine

---

ci-builder-image/Dockerfile
makefile.include
test/test-image

Just make sure at least _something_ is listening on the management interface. Not the full implementation as proposed in #53, but it's better than nothing 😄
I will update the `vrnetlab/ci-builder` image in docker hub too.

Basic smoke test for SSH management connectivity

---

.github/workflows/test.yml
.gitlab-ci.yml
Makefile
c8000v/Makefile
c8000v/README.md
c8000v/docker/Dockerfile
c8000v/docker/launch.py
topology-machine/topomachine

This started of as a copy of the (now legacy) `csr` platform, but has since been improved to:
- handle minor differences / new config defaults in the bootstrap script,
- use vmxnet3 NIC type because that is the only where dot1q VLAN tagged frame processing works,
- make the install phase more robust.
Naming things is hard. I initially used `cat8000v` when I started, but now I see the more established name is `c8000v`. Un-🐈‍⬛ before merge?

Add Catalyst 8000v

---

topology-machine/README.md
topology-machine/example-hltopo.json
topology-machine/example-lltopo.json
topology-machine/topomachine

In some rare cases we want the link between devices to be created on a specific (static) interface. It is now possible to specify the desired numeric interface ID in the p2p or hub link specifications:
{"p2p": {"pe": ["cpe:3"] }}
Under normal circumstances the "pe" and "cpe" devices would be connected on the first available interface - 1. We can override "cpe" interface assignment by providing the value after the name.

Teach topomachine to use static interface assignment

---

c8000v/docker/launch.py
common/vrnetlab.py
csr/docker/launch.py
nxos/docker/launch.py
nxos9kv/docker/launch.py
openwrt/docker/launch.py
routeros/docker/launch.py
sros/docker/launch.py
ucpe-oneos/docker/launch.py
veos/docker/launch.py
vmx/docker/launch.py
vqfx/docker/launch.py
vrp/docker/launch.py
vsr1000/docker/launch.py
xrv/docker/launch.py
xrv9k/docker/launch.py

We expose the existing command-line arguments as environment variables to offer an alternative method of configuring the container. This is helpful in combination with containerlab, where containerlab provides a partial list of arguments for username, password, hostname and connection-mode, leaving no option for the user to append to it.

Pull default launch.py args from env vars
